import Head from "next/head";
import { Overpass } from "next/font/google";
import clsx from "clsx";

const font = Overpass({
  subsets: ["latin-ext"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(font.className, "flex min-h-screen flex-col")}>
        <nav className="flex items-center bg-blue-500 px-4 py-4">
          <h2 className="text-xl font-semibold leading-relaxed text-gray-100">
            Banking.EdwardJones.com
          </h2>
        </nav>
        <div className="grid grow place-items-center px-20">
          <button
            onClick={async () => {
              const response = await fetch("/api/fetchsomethingelse");
              const data = (await response.json()) as { message: string };
              console.log(data);
            }}
            className="rounded bg-orange-500 px-4 py-2 text-white hover:bg-orange-600 focus:outline-none focus:ring-2 focus:ring-orange-600 focus:ring-opacity-50"
          >
            Fetch from Banking.EdwardJones.com
          </button>
        </div>
      </main>
    </>
  );
}
