import Head from "next/head";
import { Overpass } from "next/font/google";
import clsx from "clsx";

const font = Overpass({
  subsets: ["latin-ext"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(font.className, "flex min-h-screen flex-col")}>
        <nav className="flex items-center bg-blue-500 px-4 py-4">
          <h2 className="text-xl font-semibold leading-relaxed text-gray-100">
            Banking.EdwardJones.com
          </h2>
        </nav>
        <div className="grid grow place-items-center px-20">Hello</div>
      </main>
    </>
  );
}
